[36mATRI[0m | 03-13 09:26:28 | ERROR nonebot >> Running matcher <Matcher from 老婆, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fb3439f5040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fb34427b4f0>
         │    └ <function MultiCommand.invoke at 0x7fb3439f90d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fb34bb68370>
           │               │       │       └ <function Command.invoke at 0x7fb3439f5af0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7fb34bb68370>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fb33a920a60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7fb34bb68370>
           │   │      │    └ <function run at 0x7fb33aa4c940>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7fb3439f18b0>
           └ <click.core.Context object at 0x7fb34bb68370>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7fb33aa3c700>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7fb33cb419d0>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7fb33cb41550>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7fb33a848700>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7fb33a848af0>
    └ <uvicorn.server.Server object at 0x7fb2cec89c10>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fb33a848b80>
           │       │   └ <uvicorn.server.Server object at 0x7fb2cec89c10>
           │       └ <function run at 0x7fb34027d4c0>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fb2cec30240>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _event_to_me at 0x7fb33cae50d0>: <Task finished name='Task-418' coro=<_event_to_me() done, defined at /usr/local/p...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7fb2ce1b02b0>
          │            │        │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None}}
          │            │        │    └ GroupMessageEvent(time=1647134781, self_id=3098828791, post_type='message', sub_type='normal', user_id=2560359315, message_ty...
          │            │        └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fb2ce1b00d0>
          │            └ <Matcher from 老婆, type=message, priority=1, temp=False>
          └ <function _run_matcher at 0x7fb33a961700>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _event_to_me at 0x7fb33cae50d0>: <Task finished name='Task-418' coro=<_event_to_me() done, defined at /usr/local/p...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7fb2ce1b02b0>
          │       │   │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None}}
          │       │   │    └ GroupMessageEvent(time=1647134781, self_id=3098828791, post_type='message', sub_type='normal', user_id=2560359315, message_ty...
          │       │   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fb2ce1b00d0>
          │       └ <function Matcher.run at 0x7fb33cb61c10>
          └ <Matcher from 老婆, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _event_to_me at 0x7fb33cae50d0>: <Task finished name='Task-418' coro=<_event_to_me() done, defined at /usr/local/p...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7fb2ce1b02b0>
          │    │          │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None}}
          │    │          │    └ GroupMessageEvent(time=1647134781, self_id=3098828791, post_type='message', sub_type='normal', user_id=2560359315, message_ty...
          │    │          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fb2ce1b00d0>
          │    └ <function Matcher.simple_run at 0x7fb33cb61b80>
          └ <Matcher from 老婆, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
          └ <Dependent call=<function _tietie_superuser at 0x7fb3399eaa60>, params=[ModelField(name='event', type=MessageEvent, required=...
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'event': GroupMessageEvent(time=1647134781, self_id=3098828791, post_type='message', sub_type='normal', user_id=2560359315, ...
                 │    └ <function _tietie_superuser at 0x7fb3399eaa60>
                 └ <Dependent call=<function _tietie_superuser at 0x7fb3399eaa60>, params=[ModelField(name='event', type=MessageEvent, required=...

  File "./src/plugins/wife/__init__.py", line 34, in _tietie_superuser
    await tietie_superuser.finish(Message(result))
          │                │      │       └ [MessageSegment(type='at', data={'qq': '2560359315'}), MessageSegment(type='text', data={'text': 'mua！'})]
          │                │      └ <class 'nonebot.adapters.onebot.v11.message.Message'>
          │                └ <classmethod object at 0x7fb33cb5cc40>
          └ <Matcher from 老婆, type=message, priority=1, temp=False>

  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 464, in finish
    await cls.send(message, **kwargs)
          │   │    │          └ {}
          │   │    └ [MessageSegment(type='at', data={'qq': '2560359315'}), MessageSegment(type='text', data={'text': 'mua！'})]
          │   └ <classmethod object at 0x7fb33cb5cbe0>
          └ <Matcher from 老婆, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 449, in send
    return await bot.send(event=event, message=_message, **kwargs)
                 │   │          │              │           └ {}
                 │   │          │              └ [MessageSegment(type='at', data={'qq': '2560359315'}), MessageSegment(type='text', data={'text': 'mua！'})]
                 │   │          └ GroupMessageEvent(time=1647134781, self_id=3098828791, post_type='message', sub_type='normal', user_id=2560359315, message_ty...
                 │   └ <function Bot.send at 0x7fb33a961c10>
                 └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fb2ce1b00d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/bot.py", line 247, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
                 │    │                      │     │      │          └ {}
                 │    │                      │     │      └ [MessageSegment(type='at', data={'qq': '2560359315'}), MessageSegment(type='text', data={'text': 'mua！'})]
                 │    │                      │     └ GroupMessageEvent(time=1647134781, self_id=3098828791, post_type='message', sub_type='normal', user_id=2560359315, message_ty...
                 │    │                      └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fb2ce1b00d0>
                 │    └ <attribute '__class__' of 'object' objects>
                 └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fb2ce1b00d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/bot.py", line 175, in send
    return await bot.send_msg(**params)
                 │              └ {'user_id': 2560359315, 'group_id': 277620613, 'message_type': 'group', 'message': [MessageSegment(type='at', data={'qq': '25...
                 └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fb2ce1b00d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/bot.py", line 208, in call_api
    return await super().call_api(api, **data)
                                  │      └ {'user_id': 2560359315, 'group_id': 277620613, 'message_type': 'group', 'message': [MessageSegment(type='at', data={'qq': '25...
                                  └ 'send_msg'
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 117, in call_api
    raise exception
          └ <ActionFailed data=None, echo={'seq': 1}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
                   │    │       │         │     │      └ {'user_id': 2560359315, 'group_id': 277620613, 'message_type': 'group', 'message': [MessageSegment(type='at', data={'qq': '25...
                   │    │       │         │     └ 'send_msg'
                   │    │       │         └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fb2ce1b00d0>
                   │    │       └ <function Adapter._call_api at 0x7fb33a96f040>
                   │    └ <nonebot.adapters.onebot.v11.adapter.Adapter object at 0x7fb33aa50b50>
                   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fb2ce1b00d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 107, in _call_api
    return _handle_api_result(
           └ <function _handle_api_result at 0x7fb33a9f5670>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/utils.py", line 81, in _handle_api_result
    raise ActionFailed(**result)
          │              └ {'data': None, 'echo': {'seq': 1}, 'msg': 'SEND_MSG_API_ERROR', 'retcode': 100, 'status': 'failed', 'wording': '请参考 go-cqhttp...
          └ <class 'nonebot.adapters.onebot.v11.exception.ActionFailed'>

nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 1}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
[36mATRI[0m | 03-13 09:27:54 | ERROR nonebot >> Running matcher <Matcher from src.plugins.ping, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):

  File "/usr/bin/nb", line 8, in <module>
    sys.exit(main())
    │   │    └ <ClickAliasedGroup main>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7fb3439f5040>
           └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7fb34427b4f0>
         │    └ <function MultiCommand.invoke at 0x7fb3439f90d0>
         └ <ClickAliasedGroup main>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7fb34bb68370>
           │               │       │       └ <function Command.invoke at 0x7fb3439f5af0>
           │               │       └ <ClickAliasedCommand run>
           │               └ <click.core.Context object at 0x7fb34bb68370>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7fb33a920a60>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'file': 'bot.py', 'app': 'app'}
           │   │      │    │           └ <click.core.Context object at 0x7fb34bb68370>
           │   │      │    └ <function run at 0x7fb33aa4c940>
           │   │      └ <ClickAliasedCommand run>
           │   └ <function Context.invoke at 0x7fb3439f18b0>
           └ <click.core.Context object at 0x7fb34bb68370>
  File "/usr/local/python3/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'file': 'bot.py', 'app': 'app'}
                       └ ()
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
    │       │     └ 'app'
    │       └ 'bot.py'
    └ <function run_bot at 0x7fb33aa3c700>
  File "/usr/local/python3/lib/python3.8/site-packages/nb_cli/handlers/deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
    │       └ <function run at 0x7fb33cb419d0>
    └ <module 'nonebot' from '/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {'app': 'bot:app'}
    │                 └ ()
    └ <function get_driver at 0x7fb33cb41550>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 168, in run
    uvicorn.run(
    │       └ <function run at 0x7fb33a848700>
    └ <module 'uvicorn' from '/usr/local/python3/lib/python3.8/site-packages/uvicorn/__init__.py'>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/main.py", line 463, in run
    server.run()
    │      └ <function Server.run at 0x7fb33a848af0>
    └ <uvicorn.server.Server object at 0x7fb2cec89c10>
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fb33a848b80>
           │       │   └ <uvicorn.server.Server object at 0x7fb2cec89c10>
           │       └ <function run at 0x7fb34027d4c0>
           └ <module 'asyncio' from '/usr/local/python3/lib/python3.8/asyncio/__init__.py'>
  File "/usr/local/python3/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fb2cec30240>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 153, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _event_to_me at 0x7fb33cae50d0>: <Task finished name='Task-4249' coro=<_event_to_me() done, defined at /usr/local/...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7fb2cd160160>
          │            │        │    │      └ {'_prefix': {'command': ('ping',), 'raw_command': '/ping', 'command_arg': []}}
          │            │        │    └ GroupMessageEvent(time=1647134869, self_id=3098828791, post_type='message', sub_type='normal', user_id=2560359315, message_ty...
          │            │        └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fb2ce1b00d0>
          │            └ <Matcher from src.plugins.ping, type=message, priority=1, temp=False>
          └ <function _run_matcher at 0x7fb33a961700>
> File "/usr/local/python3/lib/python3.8/site-packages/nonebot/message.py", line 202, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _event_to_me at 0x7fb33cae50d0>: <Task finished name='Task-4249' coro=<_event_to_me() done, defined at /usr/local/...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7fb2cd160160>
          │       │   │    │      └ {'_prefix': {'command': ('ping',), 'raw_command': '/ping', 'command_arg': []}}
          │       │   │    └ GroupMessageEvent(time=1647134869, self_id=3098828791, post_type='message', sub_type='normal', user_id=2560359315, message_ty...
          │       │   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fb2ce1b00d0>
          │       └ <function Matcher.run at 0x7fb33cb61c10>
          └ <Matcher from src.plugins.ping, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _event_to_me at 0x7fb33cae50d0>: <Task finished name='Task-4249' coro=<_event_to_me() done, defined at /usr/local/...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7fb2cd160160>
          │    │          │    │      └ {'_prefix': {'command': ('ping',), 'raw_command': '/ping', 'command_arg': []}}
          │    │          │    └ GroupMessageEvent(time=1647134869, self_id=3098828791, post_type='message', sub_type='normal', user_id=2560359315, message_ty...
          │    │          └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fb2ce1b00d0>
          │    └ <function Matcher.simple_run at 0x7fb33cb61b80>
          └ <Matcher from src.plugins.ping, type=message, priority=1, temp=False>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
          └ <Dependent call=<function ping_handle at 0x7fb2cf9b4b80>, params=[ModelField(name='bot', type=Bot, required=True), ModelField...
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
                 │    │      └ {'bot': <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fb2ce1b00d0>, 'event': GroupMessageEvent(time=1647134869, self_id=3...
                 │    └ <function ping_handle at 0x7fb2cf9b4b80>
                 └ <Dependent call=<function ping_handle at 0x7fb2cf9b4b80>, params=[ModelField(name='bot', type=Bot, required=True), ModelField...

  File "./src/plugins/ping.py", line 15, in ping_handle
    await ping.send(result)
          │    │    └ 'Pong!   (108 ms)'
          │    └ <classmethod object at 0x7fb33cb5cbe0>
          └ <Matcher from src.plugins.ping, type=message, priority=1, temp=False>

  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/matcher.py", line 449, in send
    return await bot.send(event=event, message=_message, **kwargs)
                 │   │          │              │           └ {}
                 │   │          │              └ 'Pong!   (108 ms)'
                 │   │          └ GroupMessageEvent(time=1647134869, self_id=3098828791, post_type='message', sub_type='normal', user_id=2560359315, message_ty...
                 │   └ <function Bot.send at 0x7fb33a961c10>
                 └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fb2ce1b00d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/bot.py", line 247, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
                 │    │                      │     │      │          └ {}
                 │    │                      │     │      └ 'Pong!   (108 ms)'
                 │    │                      │     └ GroupMessageEvent(time=1647134869, self_id=3098828791, post_type='message', sub_type='normal', user_id=2560359315, message_ty...
                 │    │                      └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fb2ce1b00d0>
                 │    └ <attribute '__class__' of 'object' objects>
                 └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fb2ce1b00d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/bot.py", line 175, in send
    return await bot.send_msg(**params)
                 │              └ {'user_id': 2560359315, 'group_id': 277620613, 'message_type': 'group', 'message': [MessageSegment(type='text', data={'text':...
                 └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fb2ce1b00d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/bot.py", line 208, in call_api
    return await super().call_api(api, **data)
                                  │      └ {'user_id': 2560359315, 'group_id': 277620613, 'message_type': 'group', 'message': [MessageSegment(type='text', data={'text':...
                                  └ 'send_msg'
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 117, in call_api
    raise exception
          └ <ActionFailed data=None, echo={'seq': 4}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/internal/adapter/bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
                   │    │       │         │     │      └ {'user_id': 2560359315, 'group_id': 277620613, 'message_type': 'group', 'message': [MessageSegment(type='text', data={'text':...
                   │    │       │         │     └ 'send_msg'
                   │    │       │         └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fb2ce1b00d0>
                   │    │       └ <function Adapter._call_api at 0x7fb33a96f040>
                   │    └ <nonebot.adapters.onebot.v11.adapter.Adapter object at 0x7fb33aa50b50>
                   └ <nonebot.adapters.onebot.v11.bot.Bot object at 0x7fb2ce1b00d0>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 107, in _call_api
    return _handle_api_result(
           └ <function _handle_api_result at 0x7fb33a9f5670>
  File "/usr/local/python3/lib/python3.8/site-packages/nonebot/adapters/onebot/v11/utils.py", line 81, in _handle_api_result
    raise ActionFailed(**result)
          │              └ {'data': None, 'echo': {'seq': 4}, 'msg': 'SEND_MSG_API_ERROR', 'retcode': 100, 'status': 'failed', 'wording': '请参考 go-cqhttp...
          └ <class 'nonebot.adapters.onebot.v11.exception.ActionFailed'>

nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 4}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
